In [1]:
import sqlite3

In [2]:
# Create a SQLite database if it doesn't exist
connection = sqlite3.connect('employee_records.db')

In [3]:
# Create a cursor object
cursor = connection.cursor()

In [4]:
cursor.execute('''
                  CREATE TABLE IF NOT EXISTS employees (
                  id INTEGER PRIMARY KEY,
                  name TEXT  NOT NULL,
                  position TEXT,
                  salary REAL)

                  '''
                  )

In [5]:
cursor.execute('''
    CREATE TABLE IF NOT EXISTS employees (
        id INTEGER PRIMARY KEY,  -- Ensures a unique identifier
        name TEXT NOT NULL CHECK(typeof(name) = 'text' AND name GLOB '*[^0-9]*'),
        position TEXT NOT NULL CHECK(typeof(position) = 'text' AND position GLOB '*[^0-9]*'),
        salary REAL CHECK(salary > 0)  -- Salary must be a positive number
    ) STRICT;
''')

In [6]:
# Creating an employees list
data = [
    (101, 'Rai', 'Developer', 75000),
    (102, 'Bobby', 'Manager', 85000),
    (103, 'Charles', 'Analyst', 65000)
]

# Inserting data into the table
cursor.executemany('INSERT INTO employees VALUES (?, ?, ?, ?)', data)

# Committing changes to the database
connection.commit()

In [7]:
cursor.execute('SELECT * FROM employees')

# Returns a single row
cursor.fetchone()

(101, 'Rai', 'Developer', 75000.0)

In [8]:
cursor.execute('SELECT * FROM employees')

# Returns all the rows
cursor.fetchall()

[(101, 'Rai', 'Developer', 75000.0),
 (102, 'Bobby', 'Manager', 85000.0),
 (103, 'Charles', 'Analyst', 65000.0)]

In [9]:
cursor.execute('SELECT * FROM employees')

# Returning two rows
cursor.fetchmany(size=2)

[(101, 'Rai', 'Developer', 75000.0), (102, 'Bobby', 'Manager', 85000.0)]

In [10]:
# pip install ipython-sql

In [11]:
%load_ext sql

In [12]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [13]:
# Connecting to the database
%sql sqlite:///employee_records.db

In [14]:
%%sql
SELECT * FROM employees;

 * sqlite:///employee_records.db
Done.

[(101, 'Rai', 'Developer', 75000.0),
 (102, 'Bobby', 'Manager', 85000.0),
 (103, 'Charles', 'Analyst', 65000.0)]